-- Member 테이블 생성
DROP TABLE IF EXISTS Member;

CREATE TABLE Member (
    member_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255),
    id VARCHAR2(255),
    pw VARCHAR2(255),
    nickname VARCHAR2(255),
    email VARCHAR2(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    is_deleted CHAR(1)
);

-- Post 테이블 생성
DROP TABLE IF EXISTS Post;

CREATE TABLE Post (
    post_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    member_id NUMBER,
    post_title VARCHAR2(255),
    post_content CLOB,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    is_deleted CHAR(1),
    FOREIGN KEY (member_id) REFERENCES Member(member_id)
);

-- Comment 테이블 생성
DROP TABLE IF EXISTS Comment;

CREATE TABLE Comment (
    comment_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    member_id NUMBER,
    post_id NUMBER,
    comment_content VARCHAR2(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    is_deleted CHAR(1),
    FOREIGN KEY (member_id) REFERENCES Member(member_id),
    FOREIGN KEY (post_id) REFERENCES Post(post_id)
);